Initial wrapper app is functiunnal

diff --git a/macos_app/BUILD/wrapper b/macos_app/BUILD/wrapper
--- a/macos_app/BUILD/wrapper
+++ b/macos_app/BUILD/wrapper
@@ -1,1 +1,201 @@
 #!/bin/sh
+
+# ATTENTION:
+# If you are reading this, you have opened the file in a text editor.
+# If you would like to *run* this example rather than *read* it, you
+# should open Terminal.app, drag this document's icon onto the terminal
+# window, bring Terminal.app to the foreground (if necessary) and hit return.
+
+# Wrapper function for interfacing to Pashua. Written by Carsten
+# Bluem <carsten@bluem.net> in 10/2003, modified in 12/2003 (including
+# a code snippet contributed by Tor Sigurdsson), 08/2004 and 12/2004.
+# As 1st argument, you must pass a configuration string
+# As 2nd argument, you may pass the encoding to use (see documentation)
+# As 3rd argument, you may pass the path to the Pashua application,
+#                  if it's not in one of the standard locations.
+pashua_run() {
+
+	# Write config file
+	pashua_configfile=`/usr/bin/mktemp /tmp/pashua_XXXXXXXXX`
+	echo "$1" > $pashua_configfile
+
+	# Find Pashua binary. We do search both . and dirname "$0"
+	# , as in a doubleclickable application, cwd is /
+	# BTW, all these quotes below are necessary to handle paths
+	# containing spaces.
+	bundlepath="Pashua.app/Contents/MacOS/Pashua"
+	if [ "$3" = "" ]
+	then
+		mypath=`dirname "$0"`
+		for searchpath in "$mypath/Pashua" "$mypath/$bundlepath" "./$bundlepath" \
+						  "/Applications/$bundlepath" "$HOME/Applications/$bundlepath"
+		do
+			if [ -f "$searchpath" -a -x "$searchpath" ]
+			then
+				pashuapath=$searchpath
+				break
+			fi
+		done
+	else
+		# Directory given as argument
+		pashuapath="$3/$bundlepath"
+	fi
+
+	if [ ! "$pashuapath" ]
+	then
+		echo "Error: Pashua could not be found"
+		exit 1
+	fi
+
+	# Manage encoding
+	if [ "$2" = "" ]
+	then
+		encoding=""
+	else
+		encoding="-e $2"
+	fi
+
+	# Get result
+	result=`"$pashuapath" $encoding $pashua_configfile | sed 's/ /;;;/g'`
+
+	# Remove config file
+	rm $pashua_configfile
+
+	# Parse result
+	for line in $result
+	do
+		key=`echo $line | sed 's/^\([^=]*\)=.*$/\1/'`
+		value=`echo $line | sed 's/^[^=]*=\(.*\)$/\1/' | sed 's/;;;/ /g'`		
+		varname=$key
+		varvalue="$value"
+		eval $varname='$varvalue'
+	done
+
+} # pashua_run()
+
+
+# Define what the dialog should be like
+# Take a look at Pashua's Readme file for more info on the syntax
+
+conf="
+# Set transparency: 0 is transparent, 1 is opaque
+*.transparency=0.95
+
+# Set window title
+*.title = GrowlRender Daemon
+
+img.type = image
+#img.label = This is Pashua's icon, scaled down a little bit 
+img.path = extra/icons/appicon.png 
+img.maxwidth = 110 img.border = 1
+
+# Introductory text
+tb.type = text
+tb.default = monitor the rendering process of a Maya scene with Mental Ray via (detailed) growl notifications.[return]Growl must be running on your system otherwise growlrender will complain. Please, use the settings below to customize GrowlRender to your needs
+tb.height = 276
+tb.width = 310
+tb.x = 110
+tb.y = 420
+
+
+# Add a filesystem browser
+ob.type = openbrowser
+ob.label = Example filesystem browser (textfield + open panel)
+ob.width=310
+ob.tooltip = Blabla filesystem browser
+
+# Define radiobuttons
+rb.type = radiobutton
+rb.label = Example radiobuttons
+rb.option = Radiobutton item #1
+rb.option = Radiobutton item #2
+rb.option = Radiobutton item #3
+rb.option = Radiobutton item #4
+rb.default = Radiobutton item #2
+
+# Add a popup menu
+pop.type = popup
+pop.label = Example popup menu
+pop.width = 310
+pop.option = Popup menu item #1
+pop.option = Popup menu item #2
+pop.option = Popup menu item #3
+pop.default = Popup menu item #2
+
+# Add a checkbox
+chk.type = checkbox
+chk.label = Pashua offers checkboxes, too
+chk.default = 1
+
+# Add a text field
+tx.type = textfield
+tx.label = Advanced - enter command line arguments here
+tx.default = Textfield content
+tx.width = 310
+
+# Add a cancel button with default label
+cb.type=cancelbutton
+
+";
+
+
+conf2="
+# Set transparency: 0 is transparent, 1 is opaque
+*.transparency=0.95
+
+# Set window title
+*.title = GrowlRender Daemon
+
+img.type = image
+#img.label = This is Pashua's icon, scaled down a little bit 
+img.path = extra/icons/appicon.png 
+img.maxwidth = 110 img.border = 1
+
+# Add a checkbox
+chk.type = checkbox
+chk.label = Pashua offers checkboxes, too
+chk.default = 1
+
+
+
+# Add a cancel button with default label
+cb.type=cancelbutton
+
+";
+# Set the images' paths relative to this file's path / 
+# skip images if they can not be found in this file's path
+icon=$(dirname "$0")'/.icon.png';
+bgimg=$(dirname "$0")'/.demo.png';
+
+if [ -e "$icon" ]
+then
+	# Display Pashua's icon
+	conf="$conf
+	     img.type = image
+	     img.x = 530
+	     img.y = 255
+	     img.path = $icon"
+fi
+
+if [ -e "$bgimg" ]
+then
+ 	# Display background image
+	conf="$conf
+	      bg.type = image
+	      bg.x = 30
+	      bg.y = 2
+	      bg.path = $bgimg"
+fi
+
+pashua_run "$conf" 
+
+echo "Pashua created the following variables:"
+echo "  tb  = $tb"
+echo "  tx  = $tx"
+echo "  ob  = $ob"
+echo "  pop = $pop"
+echo "  rb  = $rb"
+echo "  cb  = $cb"
+echo ""
+
+pashua_run "$conf2"
